In [15]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

In [16]:
img = cv2.imread('text1.jpeg',0)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)
erosion2 = cv2.erode(img, kernel, iterations= 5)

In [17]:
cv2.imshow('img', erosion)
cv2.imshow('img2', erosion2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
dilation = cv2.dilate(img, kernel, iterations=1)

In [19]:
cv2.imshow('img', dilation)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
#노이즈 제거

In [21]:
cv2.imshow('img', opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

In [23]:
cv2.imshow('img', closing)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

In [26]:
cv2.imshow('img', gradient)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)

In [28]:
cv2.imshow('img', tophat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

In [ ]:
cv2.imshow('img', blackhat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [32]:
cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [33]:
cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)