In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('test.jpg')

px = img[100, 100]
print(px)

[180 136 123]


In [3]:
color = img[100, 100, 0]
print(color)

180


In [5]:
img[100, 100] = [255,255,255]
print(img[100, 100])

[255 255 255]


In [6]:
cv2.imshow('imgg', img)
k = cv2.waitKey(0) & 0xFF
if k == 27:
    cv2.destroyAllWindows()

In [10]:
px = img[150, 150]
print(px)

[102  68  46]


In [9]:
for x in range(100):
    for y in range(50):
        img[100+y, 100+x] = [0,0,0]
cv2.imshow('imgg', img)
k = cv2.waitKey(0) & 0xFF
if k == 27:
    cv2.destroyAllWindows()

In [11]:
print(img.item(10, 10, 0), img.item(10, 10, 1), img.item(10, 10, 2))

252 209 168


In [15]:
copy = img[280:340, 330:390]
img[100:100, 100:160] = copy

cv2.imshow('imgg', img)
k = cv2.waitKey(0) & 0xFF
if k == 27:
    cv2.destroyAllWindows()